### ISSUE TITLE
Level does not load; server authentication timeout

### ISSUE THREAD

**Issue by superewald** [MiniDigger/Godotcraft#2]
The client seems to be unable to connect to a local vanilla minecraft server due to some connection error.

## current behavior

After connecting to a local vanilla minecraft server (v1.15.2), the client only shows an empty 3d world (a simple pane and skybox). 

<details><summary>Screen recording</summary>

![no-level](https://user-images.githubusercontent.com/34782055/157060960-e295fd08-4f29-4bb9-908b-33bd09a94739.gif)
</details>

## expected behavior

According to the status in readme, the client should at least render simple blocks/chunks as shown in the images.

## environment

- Kubuntu 20.04
- Godot v3.4.2 (Mono)
- .Net Core 3.1
- Minecraft vanilla server v1.15.2

## reproduction

1. clone godotcraft
2. (fix Newtonsoft.Json dependency by) `dotnet add package Newtonsoft.Json --version 12.0.3`
3. copy assets from InventiveTalent to `user://mcassets`
4. copy data/reports from `java -cp server-1.15.2.jar net.minecraft.data.Main --all` output to `user://mcassets` (will override some files from InventiveTalent)
5. start server `java -Xmx1024M -Xms1024M -jar server-1.15.2.jar`
6. start client and connect to local server

## logs/output

The server throws an timeout for the authentication:
```
...
[16:00:17] [Server thread/INFO]: Preparing spawn area: 97%
[16:00:17] [Server thread/INFO]: Time elapsed: 17396 ms
[16:00:17] [Server thread/INFO]: Done (44.300s)! For help, type "help"
[16:00:19] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2147ms or 42 ticks behind
[16:04:50] [Server thread/INFO]: com.mojang.authlib.GameProfile@64167e6d[id=<null>,name=MiniDiggerTest,properties={},legacy=false] (/127.0.0.1:33138) lost connection: Disconnected
[16:06:39] [Server thread/INFO]: com.mojang.authlib.GameProfile@674efa29[id=<null>,name=MiniDiggerTest,properties={},legacy=false] (/127.0.0.1:33142) lost connection: Timed out
```

And the client throws this error:
```
E 0:00:23.228   get_available_bytes: Condition "!is_open()" is true. Returned: -1
  <C++ Source>  drivers/unix/net_socket_posix.cpp:708 @ get_available_bytes()
  <Stack Trace> :0 @ Int32 Godot.NativeCalls.godot_icall_0_5(IntPtr , IntPtr )()
                StreamPeer.cs:96 @ Int32 Godot.StreamPeer.GetAvailableBytes()()
                MinecraftClient.cs:58 @ void Godotcraft.scripts.network.protocol.MinecraftClient._Process(Single )()
```

**Comment by MiniDigger** [comment]
oh lol, didn't expect people to actually try this out
I know that it worked when I last used it, only thing that I can think of is that your server is not in offline mode? I didn't implement authentication yet.

**Comment by superewald** [comment]
> oh lol, didn't expect people to actually try this out 

And I didn't expect an answer that fast :D btw the repo has 25 stars so I guess I'm not the only one :)

> I know that it worked when I last used it, only thing that I can think of is that your server is not in offline mode? I didn't implement authentication yet.

You're right, after switiching `online-mode=false` the authentication timeout is gone.
The client exception still remains but it does log packets now and yells some other issues (index out of bounds and such) but I should be able to fix them. 

If you don't mind I have a few questions about the project itself:
1. you're targeting v1.15.2 but it should work with later versions in theory, right ?
2. is FPS expected to be low at the current state ? my machine is low also but 10 FPS is unexpected for me as currently no chunks are rendered

*Edit²:* Nevermind, I'm stupid and cant read. Ive placed the server data into mcassets rather than mcdata, its working now :)
![Screenshot_20220307_203131](https://user-images.githubusercontent.com/34782055/157104953-bffac00a-876f-474f-b47c-fd8aff8a8ff9.png)

**Comment by MiniDigger** [comment]
1.15.2 was latest at the time when I played with this, thats why that is targeted, newer versions will need changes as the protocol for chunks changed (among other things), but thats doable. 
I don't exactly remember how performance was, and I generally have no idea on how to properly mesh stuff, so if its low that wouldn't surprise me, there is a ton of optimization opportunities. 
you can see the code for meshing here: https://github.com/MiniDigger/Godotcraft/blob/968506f6ba8dcb7b5cb9cbdc9cdb71998e4a815a/scripts/renderer/ChunkRenderer.cs#L7
iirc the collision thing was what make chunk loading slow, it should be replaced with way simpler collision shapes. if you press P it will cycle thru some debug views.

generally, I would love to revisit this project, but I don't have time right now and when I revisit in the future, rewriting it in godot 4 (and maybe learning about shaders, lmao) would make more sense.

>  btw the repo has 25 stars so I guess I'm not the only one :) 

fair point, lol, didn't realize people found this little experiment. it was my first c# and my first godot project so its prolly all kinda of horrible, especially the network code.
I do have a discord, which is mostly dead, (https://discord.gg/M3gpqQJ) or you can find me on papers discord (https://discord.gg/papermc) if you wanna chat more about this, just ping me, not super sure I can be of much help tho since its quite old.
